### ISSUE TITLE
Dev content review 2

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-contract-testing#1]
Should not hotspot English words

- [x] Missing title
- **What you’ll learn**
  - [x] "...the JVM `system` properties..." -> "...the JVM system properties..."
     - no backticks
- **Implementing pact test in the inventory service**
  - [x] "...class contains a `mock provider` that ..." -> either
    - "...class contains a `PactProviderRule` mock provider that ..." or
    - "...class contains a `mockProvider` mock provider that ..."
  - [x] "The `RequestResponsePact` method defines..." -> "The `createPactEncoding()` method defines..."
    - [x] should highlight the whole method instead of return
  - [x] no wrap lines in InventoryPactIT.java
  - [x] "The test sends a real request to the `mock provider`." -> "The test sends a real request by the `getUrl()` method of  the mock provider."
  - [x] "Finally, the `unit test` confirms that the response is correct." -> "Finally, the `assertEquals()` unit test confirms that the response is correct." 
  - [x] "The pact framework provides an `extension` that ..." -> "The pact framework provides an `maven` extension that ..."
  - [x] "It contains the `endpoint` URL... the `location` at which..." -> "It contains the endpoint URL by the `serviceProvider` element... the location by the `pactFileDirectory` element at which..."
- **Verifying the pact in pact broker**
  - [x] "...that a new entry was added."
    - I doubt to use past tense
  - [x] "...the `Last verified` column..."
    - no need to backtick
  - [x] "... about each interaction that was created."
    - I doubt to use past tense
- **Implementing pact test in the system service**
  - [x] "The dependency also provides a `JUnit5 Invocation Context Provider` to write..." -> either
    - "The dependency also provides a JUnit5 invocation context provider by the `@ExtendWith` annotation to write..." or
    - "The dependency also provides a JUnit5 invocation context provider by the `pactVerificationTestTemplate` method to write..." or
  - [x] add empty line before `@BeforeAll` and `@BeforeEach`
  - [x] "... for `pact.verifier.publishResults` so that ..." -> "... for `pact.verifier.publishResults` property so that ..."
  - [x] "The test target is defined in the `PactVerificationContext` to point ..." -> "The test target is defined in the `PactVerificationContext` context to point ..."
  - [x] "... the `.given()` parameter..." -> "... the `given()` parameter..."
  - [x] "`Junit5 pact provider` dependency is..." -> "The `junit5` pact provider dependency is..."
  - [x] "...the `pact.provider.version` is ..." ->  "...the `pact.provider.version` element is ..."
- **Tearing down the environment**
  - [x] need to be clear to stop the system and inventory services

**Comment by meswan** [comment]
Addressed!
