### ISSUE TITLE
Content review feedback

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/draft-guide-contract-testing#15]
@meswan Looking good! Here's my content review feedback: 

### Global
- [x] Hyphenate "consumer driven" --> "consumer-driven"
- [x] "pact broker" --> "Pact Broker" - https://docs.pact.io/pact_broker/docker_images/
- [x] "Pact" needs to be capitalized when referring to the technology. For example, " integrating pact into continuous integration (CI) and continuous delivery (CD) pipelines." --> " integrating Pact into continuous integration (CI) and continuous delivery (CD) pipelines."
- [x] It looks like sometimes we talk about the "pact broker" and sometimes it's the "pact broker application". Is there a difference? If not, let's use one consistently. 

### What you’ll learn
- [x] I think that the second link with hyperlinked text of "Pact" doesn't need to be a link unless you have a more specific link about the Pact framework. The link takes users to the same place that the first "Pact" link goes. 

### Getting started
- [x] "Start the pact broker application:" --> "Run the following command to start the Pact Broker:"
- [x] "Go to http://localhost:9292/ to confirm that you can access the pact broker’s UI." --> Maybe this should be "Go to the http://localhost:9292/ URL to confirm that you can access the pact broker’s UI, as shown in the following image:" 
- [x] I think we need more space between the end of the image and the next paragraph. Can we insert a blank line there? 

### Implementing pact test in the inventory service
- [x] I don't think you need the first paragraph at all, as it reiterates what was said in the Getting started section
- [x] "A contract between inventory and system microservice is known as a pact. Each pact is a collection of interactions that are defined in the InventoryPactIT class." --> "The contract between the inventory and system services is known as a pact. Each pact is a collection of interactions. In this guide, those interactions are defined in the InventoryPactIT class."
- [ ] "Replace the inventory maven project file." --> "Create the inventory maven project file." - because this file is being mentioned for the first time

### Verifying the pact in pact broker
- [x] Add a blank line between the image and the following paragraph

### Implementing pact test in the system service
- [x] Add a blank line between the code snippet about dev mode and the "Create the SystemBrokerIT class file." arrow
- [x] Junit5  in the hotspot should maybe be junit5, since that's the literal value from the code 
- [ ] "Replace the system maven project file." --> "Create the system maven project file." - because this file is being mentioned for the first time

### Verifying the contract
- [ ] "Replace the SystemResource class file." --> "Create the SystemResource class file." - because this file is mentioned for the first time
- [x] Add a blank line between the image and the next paragraph

**Comment by meswan** [comment]
Addressed.
