### ISSUE TITLE
MacOS peer review

### ISSUE THREAD

**Issue by griffinhadfield** [OpenLiberty/draft-guide-contract-testing#2]
## Peer Review conducted on Mac

Functionality
---
- [x] Check that the guide has working instructions and sample code
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---

`README.adoc` checks:
- [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
- [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check that the pom.xml, server.xml, etc files are clean
    - [x] Remove any dependencies and features that are not required
    - [x] Ensure that the parent pom.xml files do not contain any dependencies, and all dependencies are specified in the children pom.xml files
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided

`pom.xml` checks (if files are present):
- [x] Check that the file follows the template found here: https://github.com/OpenLiberty/draft-guides-template/blob/master/finish/pom.xml
- [x] Check that the following dependencies are included in all of the `pom.xml` files:
```
<!-- Provided dependencies -->
<dependency>
  <groupId>jakarta.platform</groupId>
  <artifactId>jakarta.jakartaee-api</artifactId>
  <version>8.0.0</version>
  <scope>provided</scope>
</dependency>

<dependency>
  <groupId>org.eclipse.microprofile</groupId
  <artifactId>microprofile</artifactId>
  <version>3.3</version>
  <type>pom</type>
  <scope>provided</scope>
</dependency>
```
- [x]  Check that the versions of plugins are directly provided and not fed in by a file property.
  - Not formatted like so:
```
    <properties>
        <!-- Plugins -->
        <version.liberty-maven-plugin>3.2</version.liberty-maven-plugin>
    </properties>

    <!-- Liberty plugin -->
    <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>${version.liberty-maven-plugin}</version>
    </plugin>
```
  - Should be formatted like so:
```
    <!-- Liberty plugin -->
    <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>3.2</version>
    </plugin>
```
- [x] Check that there are 4 spaces per indent for proper formatting
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable

Overall checks:
- [x] Check the consistency of guide with the template and other guides
- [x] Check the quality of code according to the best coding practices
- [x] Check that all licensing statements are properly stated in all files, with the correct year (Should be present in all Java files + the `index.html`)
- [x] Check that the directories are properly structured
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [ ] Check the `attribution` statement is accurate for the guide
- [ ] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

---

- [ ] Additional tests where applicable: 
    - [ ] Define test coverage and review with team (including guide contributor, if available)
    - [ ] Define detail test cases 
    - [ ] Consider corner cases targeting the specific guide
    - [ ] Consider corner cases UI tests
    - [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
    - [ ] Make sure the index.html information is correct by visiting the root, e.g. `http://localhost:9080`
- [ ] Consider building with both Maven and Gradle build tools 
- [ ] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created
- [ ] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots 
- [x] Test the guide end-to-end with working instruction and sample code
- [ ] Perform all the defined test cases

**Comment by griffinhadfield** [comment]
## Functionality

- [ ] I am receiving the same error as outlined in https://github.com/OpenLiberty/draft-guide-contract-testing/issues/3.

## What you'll learn

- [x] I don't think the `Pact` and `Pact broker` subsection titles are necessary if there is only a single sentence under each. 


## Implementing the pact test in the inventory service
- [x] When asking the user to create the `InventoryPactIT.java` file, instruction, I think `inventory/` should be added to the file path. 
- [x] Regarding the following sentence:
 > Open a new command-line session and navigate to the start/inventory directory to publish the generated pact file to the pact broker by using:

I think the sentence could be split into two, and the "by using" be replaced with "by running the following command". Perhaps replace this sentence with "Open a new command-line session and navigate to the `start/inventory` directory. Publish the generated pact file to the pact broker by running the follow command:"

## Verifying the pact in pack broker

- [ ] I experience the same image distortion outlined in https://github.com/OpenLiberty/draft-guide-contract-testing/issues/3
- [x] Regarding the following sentence:
 > Refresh the pact broker URL at http://localhost:9292/ to verify...

Perhaps replace URL with "page" or something similar. Doesn't seem correct to ask the user to refresh the *URL* itself.

- [x] Regarding the following sentence:
> You can also see the interactions URL at http:// ... 

I don't think calling it the "interactions URL" is correct. Perhaps this can be rephrased to: "You can see insights about each interaction by navigating to the [link] URL." 


## Implementing the pact test in the system service
- [x] When asking the user to create the `SystemBrokerIT.java` file, instruction, I think `system/` should be added to the file path. 

## Verifying the contract:

- [x] Regarding the following sentence:
> In the command-line session where the system microservice was started...

"system" should have tics around it.

- [x] Regarding the following sentence:
> When completed, refresh the pact broker URL at http://localhost:9292/ ...

Replace URL with "page" or something similar. 

## Tearing down the environment 

- [ ] Regarding the following sentence:
> Navigate back to ` /guide-contract-testing` directory...

Missing "the" - replace with "Navigate back to the ` /guide-contract-testing` directory..."

## Other 

- [x] Missing the Jakarta dependency in the `pom.xml`s:
```
<dependency>
  <groupId>jakarta.platform</groupId>
  <artifactId>jakarta.jakartaee-api</artifactId>
  <version>8.0.0</version>
  <scope>provided</scope>
</dependency>
```
 - [ ] Missing travis test script.

**Comment by meswan** [comment]
addressed
