### ISSUE TITLE
Styling issue with guide

### ISSUE THREAD

**Issue by gljrobinson** [OpenLiberty/draft-guide-contract-testing#22]
Text font and size differs at the "A Pact between System and Inventory" subsection. This needs to be changed to match the rest of the guide.

**Comment by gkwan-ibm** [comment]
hi @GraceJansen  The "A pact between System and Inventory" is from an image that comes from `http://localhost:9292/pacts/provider/System/consumer/Inventory/latest`. I doubt we can change it.

**Comment by gljrobinson** [comment]
Ok, no worries then. I understand why it can't be changed.

**Comment by gkwan-ibm** [comment]
asking a design to show the screenshots clearer

**Comment by gkwan-ibm** [comment]
close
- the diagrams was shrank and align to right so that they won't be treated as normal text
