### ISSUE TITLE
Windows Peer Review

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/draft-guide-contract-testing#3]
# Overall

- [ ] Should have a `.gitignore` file to exclude files such as those in the `target` directory

# Implementing pact test in the inventory service

- [x] I think the instructions to create the `pom.xml` and `InventoryPactIT.java` files should be before the descriptions of their contents
- [x] "When integrating pact in a CI/CD pipeline"
  - Not sure if it is correct to say "When integrating pact verification" or "When integrating pacts" instead

# Verifying the pact in pact broker

- [ ] Unsure if this is an issue with my browser or the image itself, but the image to show what to expect at `localhost:9292` seems to be distorted, see attached picture

<img width="497" alt="Screen Shot 2020-12-22 at 3 23 26 PM" src="https://user-images.githubusercontent.com/24989956/102930068-c3132a00-4469-11eb-9a17-d5533fa0f281.png">

# Implementing pact test in the inventory service

- [x] Same as inventory section, I think instructions to create files should be before their descriptions
- [x] "`Junit5` pact provider dependency" -> "**The** `Junit5` pact provider dependency"

# Verifying the contract

- [ ] Verification fails, I get the following error when I run the tests in dev mode, timestamp at `localhost:9292` also indicated verifcation failure

```
Verifying a pact between Pact between Inventory (1.0-SNAPSHOT) and System

  Notices:
    1) The pact at http://localhost:9292/pacts/provider/System/consumer/Inventory/pact-version/b1690f3848e723594a22649afe98af166c504b1a is being verified because it matches the following configured selection criterion: latest pact for a consumer version tagged 'open-liberty-pact'

  [from Pact Broker http://localhost:9292/pacts/provider/System/consumer/Inventory/pact-version/b1690f3848e723594a22649afe98af166c504b1a]
  Given os.encoding is UTF-8
  a request for os encoding entity
    returns a response which
      has status code 200 (FAILED)
      includes headers
        "Content-Type" with value "application/json" (FAILED)
      has a matching body (FAILED)

Failures:

1) Verifying a pact between Inventory and System - a request for os encoding entity

    1.1) StatusMismatch: expected status of 200 but was 500

    1.2) HeaderMismatch: Expected header 'Content-Type' to have value 'application/json' but was 'text/html;charset=ISO-8859-1'

    1.3) BodyTypeMismatch: Expected a response type of 'application/json' but the actual type was 'text/html'


[main] WARN au.com.dius.pact.provider.DefaultTestResultAccumulator - Not all of the 3 were verified. The following were missing:
[main] WARN au.com.dius.pact.provider.DefaultTestResultAccumulator -     a request for the version

Verifying a pact between Pact between Inventory (1.0-SNAPSHOT) and System

  Notices:
    1) The pact at http://localhost:9292/pacts/provider/System/consumer/Inventory/pact-version/b1690f3848e723594a22649afe98af166c504b1a is being verified because it matches the following configured selection criterion: latest pact for a consumer version tagged 'open-liberty-pact'

  [from Pact Broker http://localhost:9292/pacts/provider/System/consumer/Inventory/pact-version/b1690f3848e723594a22649afe98af166c504b1a]
  Given version is 1.1
  a request for the version
    returns a response which
      has status code 200 (OK)
      has a matching body (OK)
[main] INFO au.com.dius.pact.provider.DefaultVerificationReporter - Published verification result of 'Failed(results=[{mismatch=StatusMismatch: expected status of 200 but was 500, type=status, interactionId=0dd4c2db01bdf48ab274c3c049d2bb7056a3618e}, {mismatch=HeaderMismatch: Expected header 'Content-Type' to have value 'application/json' but was 'text/html;charset=ISO-8859-1', interactionId=0dd4c2db01bdf48ab274c3c049d2bb7056a3618e}, {mismatch=BodyTypeMismatch: Expected a response type of 'application/json' but the actual type was 'text/html', type=body, interactionId=0dd4c2db01bdf48ab274c3c049d2bb7056a3618e}], description=Response status did not match, Headers had differences, Body had differences)' for consumer 'Consumer(name=Inventory)'
```

- [x] "When integrating pact in a CI/CD pipeline"
  - Not sure if it is correct to say "When integrating pact verification" or "When integrating pacts" instead
- [ ] Similar image distortion as noted in the "Verifying the pact in pact broker" section
- [x] "meet the expectation of the `inventory` microservice" -> "meet the expectation**s** of the `inventory` microservice"

**Comment by meswan** [comment]
addressed
