### ISSUE TITLE
Dev content review feedback

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-contract-testing#9]
- [x] "Create the InventoryPactIT.java file." -> "Create the InventoryPactIT class.".
- [x] "Replace the inventory pom file." -> "Replace the inventory maven project file."
- [x] "Create the SystemBrokerIT.java file." -> "Create the SystemBrokerIT class."
- [ ] "Replace the system pom file." -> "Replace the system maven project file."

**Comment by meswan** [comment]
Addressed
